### ISSUE TITLE
Dummy elf.Map structure missing Fd() method

### ISSUE THREAD

**Issue by paskal** [iovisor/gobpf#238]
Hi there!

I'm trying to make sense of the code I inherited which is compiling and working under Linux but doesn't even tests on my macOS machine. The error I am observing on `go test` run is the following: `x.Fd undefined (type *elf.Map has no field or method Fd)`.

Map structure mentioned in error message is defined here:

https://github.com/iovisor/gobpf/blob/3fa68425afb2ecdf601da034f8326468df066332/elf/elf_unsupported.go#L8

What would you suggest me to do in that situation, try to make part of the project built only on Linux by using build tags, or try to add this method to this (dummy?) `Map` structure? If the latter option, what should it do?

I am not familiar with this project and if I have too many misconceptions in my mind, please let me know where I am wrong.

**Comment by paskal** [comment]
@alban would you be so kind as to help me with that? Your advice would be highly appreciated!

**Comment by alban** [comment]
@paskal you can add a dummy implementation in elf_unsupported.go:
```
func (m *Map) Fd() int {
  return -1
}
```
following the same prototype as in https://github.com/iovisor/gobpf/blob/3fa68425afb2ecdf601da034f8326468df066332/elf/elf.go#L827-L829

Those 2 files use build tags that specify which one is running on Linux and on macOS:
- `// +build linux` (elf_unsupported.go)
- `// +build !linux` (elf.go)

That would allow you to run some unit tests with `go test` on macOS but in the end gobpf can only run properly on Linux since BPF is a Linux feature.

**Comment by paskal** [comment]
Thank you a lot for the prompt answer! I'm trying to build a package somehow and syntax error is preventing me from doing so, your proposed dummy implementation would help me greatly. I would be able to write a separate set of tests for Linux and non-Linux systems in that case.
